<?php

namespace Phramework\Validate;

use PHPUnit\Framework\Attributes\DataProvider;
use PHPUnit\Framework\TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015 - 2016-10-05 at 22:11:07.
 */
class BooleanValidatorTest extends TestCase
{

    /**
     * @var BooleanValidator
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new BooleanValidator();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
    }

    public static function validateSuccessProvider(): array
    {
        //input, expected
        return [
            'integer 1' => [1, true],
            'string 1' => ['1', true],
            'boolean true' => [true, true],
            'string true lowercase' => ['true', true],
            'string true uppercase' => ['TRUE', true],
            'string yes' => ['yes', true],
            'string on' => ['on', true],
            'integer 0' => [0, false],
            'string 0' => ['0', false],
            'boolean false' => [false, false],
            'string false lowercase' => ['false', false],
            'string false uppercase' => ['FALSE', false],
            'string no' => ['no', false],
            'string off' => ['off', false]
        ];
    }

    public static function validateFailureProvider(): array
    {
        //input
        return [
            'string 100' => ['100'],
            'string 01' => ['01'],
            'integer 10' => [10],
            'integer -1' => [-1],
            'integer 124' => [124],
            'greek string' => ['τρθε'],
            'string positive' => ['positive'],
            'string negative' => ['negative']
        ];
    }

    public function testConstruct(): void
    {
        $validator = new BooleanValidator();
        $this->assertInstanceOf(BooleanValidator::class, $validator);
    }

    #[DataProvider('validateSuccessProvider')]
    public function testValidateSuccess($input, bool $expected): void
    {
        $return = $this->object->validate($input);

        $this->assertIsBool($return->value);
        $this->assertSame($expected, $return->value);
        $this->assertTrue($return->status);
    }

    #[DataProvider('validateFailureProvider')]
    public function testValidateFailure($input): void
    {
        $return = $this->object->validate($input);

        $this->assertFalse($return->status);
    }

    /**
     * Validate against common enum keyword
     */
    public function testValidateCommon(): void
    {
        $validator = (new BooleanValidator());

        $validator->enum = [true];

        $return = $validator->validate(true);
        $this->assertTrue(
            $return->status,
            'Expect true since true is in enum array'
        );

        $return = $validator->validate(false);
        $this->assertFalse(
            $return->status,
            'Expect false since false is not in enum array'
        );
    }

    public function testGetType(): void
    {
        $this->assertEquals('boolean', $this->object->getType());
    }
}
