<?php

namespace Phramework\Validate;

use PHPUnit\Framework\Attributes\DataProvider;
use PHPUnit\Framework\TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015 - 2016-10-05 at 22:11:07.
 */
class EmailValidatorTest extends TestCase
{

    /**
     * @var EmailValidator
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new EmailValidator(10, 30);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
    }

    public static function validateSuccessProvider(): array
    {
        //input, expected
        return [
            'gmail' => ['nohponex@gmail.com'],
            'underscore' => ['nohponex_under@gmail.com'],
            'co.uk' => ['nohponex@mail.co.uk'],
        ];
    }

    public static function validateFailureProvider(): array
    {
        //input
        return [
            'string' => ['100'],
            'less than 10 characters' => ['nx@ma.il'],
            'dotless' => ['nohponex@gmailcom'],
            'longer' => ['nohponex_long_long_long_long_long@gmail.com'],
            'without@' => ['dasdjs#sdads.fd'],
            'number' => [124],
        ];
    }

    public function testConstruct(): void
    {
        $validator = new EmailValidator();
        $this->assertInstanceOf(EmailValidator::class, $validator);
    }

    #[DataProvider('validateSuccessProvider')]
    public function testValidateSuccess(string $input): void
    {
        $return = $this->object->validate($input);

        $this->assertIsString($return->value);
        $this->assertTrue($return->status);
    }

    #[DataProvider('validateFailureProvider')]
    public function testValidateFailure(mixed $input): void
    {
        $return = $this->object->validate($input);

        $this->assertFalse($return->status);
    }

    public function testCreateFromJSON(): void
    {
        $json = '{
            "type": "email"
        }';

        $validationObject = BaseValidator::createFromJSON($json);

        $this->assertInstanceOf(EmailValidator::class, $validationObject);
    }

    public function testGetType(): void
    {
        $this->assertEquals('email', $this->object->getType());
    }
}
