<?php

namespace Phramework\Validate;

use PHPUnit\Framework\Attributes\DataProvider;
use PHPUnit\Framework\TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015 - 2016-10-05 at 22:11:07.
 */
class EnumValidatorTest extends TestCase
{

    /**
     * @var EnumValidator
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new EnumValidator(['1', '2', [1, 2, 3], 'ok', 5], true);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
    }

    public static function validateSuccessProvider(): array
    {
        //input, expected
        return [
            'string 1' => ['1', '1'],
            'string 2' => ['2', '2'],
            'string ok' => ['ok', 'ok'],
            'integer 5' => [5, 5],
            'array' => [[1, 2, 3], [1, 2, 3]],
        ];
    }

    public static function validateFailureProvider(): array
    {
        //input
        return [
            'integer 1 (wrong type)' => [1],
            'integer 2 (wrong type)' => [2],
            'string 5 (wrong type)' => ['5'],
            'not in enum 4' => [4],
            'not in enum 7' => ['7'],
            'not in enum string' => ['string']
        ];
    }

    public function testConstruct(): void
    {
        $validator = new EnumValidator(
            ['1', '2', 'ok', 5],
            true
        );
        $this->assertInstanceOf(EnumValidator::class, $validator);
    }

    #[DataProvider('validateSuccessProvider')]
    public function testValidateSuccess(mixed $input, mixed $expected): void
    {
        $return = $this->object->validate($input);

        $this->assertTrue($return->status);
        $this->assertSame($expected, $return->value);
    }

    #[DataProvider('validateFailureProvider')]
    public function testValidateFailure(mixed $input): void
    {
        $return = $this->object->validate($input);

        $this->assertFalse($return->status);
    }

    public function testCreateFromJSON(): void
    {
        $json = '{
            "type": "enum",
            "enum": [1, 2, 3]
        }';

        $validationObject = BaseValidator::createFromJSON($json);

        $this->assertInstanceOf(EnumValidator::class, $validationObject);
    }

    public function testCreateFromJSONAndValidate(): void
    {
        $json = '{
            "type": "enum",
            "enum": [1, 2, 3],
            "validateType": false
        }';

        $validationObject = BaseValidator::createFromJSON($json);

        $this->assertInstanceOf(EnumValidator::class, $validationObject);

        $this->assertSame(1, $validationObject->parse('1'));
        $this->assertSame(1, $validationObject->parse(1));
    }

    public function testCreateFromJSONAndValidateType(): void
    {
        $this->expectException(\Phramework\Exceptions\IncorrectParametersException::class);
        $json = '{
            "type": "enum",
            "enum": [1, 2, 3],
            "validateType": true
        }';

        $validationObject = BaseValidator::createFromJSON($json);

        $validationObject->parse('1');
    }

    public function testGetType(): void
    {
        $this->assertEquals('enum', $this->object->getType());
    }
}
