<?php

namespace Phramework\Validate;

use PHPUnit\Framework\Attributes\DataProvider;
use PHPUnit\Framework\TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015 - 2016-10-05 at 20:04:03.
 */
class IntegerValidatorTest extends TestCase
{

    /**
     * @var IntegerValidator
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new IntegerValidator(-1000, 1000, true);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void {}

    public static function validateSuccessProvider(): array
    {
        //input, expected
        return [
            'string "100"' => ['100', 100],
            'integer 124' => [124, 124],
            'integer 0' => [0, 0],
            'integer -10' => [-10, -10],
            'integer -99' => [-99, -99]
        ];
    }

    public static function validateFailureProvider(): array
    {
        //input
        return [
            'hex string' => ['-0x'],
            'alpha string' => ['abc'],
            'plus string' => ['+xyz'],
            'double plus string' => ['++30'],
            'exclusive minimum' => [-1000], //should fail because of exclusiveMinimum
            'out of bounds minimum' => [-10000000],
            'out of bounds maximum' => [10000000],
            'out of bounds string' => ['-1000000000'],
            'float value' => [1.4],
            'negative float value' => [-13.5]
        ];
    }

    public function testConstruct(): void
    {
        $validator = new IntegerValidator(
            0,
            1
        );
        $this->assertInstanceOf(IntegerValidator::class, $validator);
    }

    public function testConstructFailure(): void
    {
        $this->expectException(\Exception::class);
        new IntegerValidator(
            'a'
        );
    }

    public function testConstructFailure2(): void
    {
        $this->expectException(\Exception::class);
        new IntegerValidator(
            1,
            'a'
        );
    }

    public function testConstructFailure3(): void
    {
        $this->expectException(\Exception::class);
        new IntegerValidator(
            1,
            2,
            null,
            null,
            'a'
        );
    }

    #[DataProvider('validateSuccessProvider')]
    public function testCreateFromJSON(string|int $input, int $expected): void
    {
        $json = '{
            "type": "integer",
            "minimum" : -1000,
            "maximum" : 1000,
            "title": "my int",
            "default": 10,
            "x-extra": "not existing"
        }';

        $validatorObject = IntegerValidator::createFromJSON($json);

        $this->assertSame(
            'my int',
            $validatorObject->title,
            'Title must be passed'
        );

        $this->assertSame(
            10,
            $validatorObject->default,
            'Default must be passed'
        );

        $this->assertObjectNotHasProperty(
            'x-extra',
            $validatorObject,
            'Attribute must not exists'
        );

        //use helper function to validate $input against this validator
        $this->validateSuccess($validatorObject, $input, $expected);
    }

    /**
     * Helper method
     */
    private function validateSuccess(IntegerValidator $object, string|int $input, int $expected): void
    {
        $return = $object->validate($input);

        $this->assertTrue($return->status);
        $this->assertIsInt($return->value);
        $this->assertSame($expected, $return->value);
    }

    #[DataProvider('validateSuccessProvider')]
    public function testValidateSuccess(string|int $input, int $expected): void
    {
        $this->validateSuccess($this->object, $input, $expected);
    }

    #[DataProvider('validateFailureProvider')]
    public function testValidateFailure(mixed $input): void
    {
        $return = $this->object->validate($input);

        $this->assertFalse($return->status);
    }

    public function testValidateFailureMultipleOf(): void
    {
        $validator = new IntegerValidator(null, null, null, null, 2);
        $return = $validator->validate(5);

        $this->assertFalse($return->status);

        $parameters = $return->errorObject->getParameters();

        $this->assertEquals('multipleOf', $parameters[0]['failure']);
    }

    /**
     * Validate against common enum keyword
     */
    public function testValidateCommon(): void
    {
        $validator = (new IntegerValidator(0, 10));

        $validator->enum = [1, 3, 5];

        $return = $validator->validate(1);
        $this->assertTrue(
            $return->status,
            'Expect true since "1" is in enum array'
        );

        $return = $validator->validate(2);
        $this->assertFalse(
            $return->status,
            'Expect false since "2" is not in enum array'
        );
    }

    public function testGetType(): void
    {
        $this->assertEquals('integer', $this->object->getType());
    }
}
