<?php

namespace Phramework\Validate;

use PHPUnit\Framework\Attributes\DataProvider;
use PHPUnit\Framework\TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015 - 2016-10-05 at 20:04:03.
 */
class NumberValidatorTest extends TestCase
{

    /**
     * @var NumberValidator
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new NumberValidator(-1000, 1000, true);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void {}

    public static function validateSuccessProvider(): array
    {
        //input, expected (float)
        return [
            'string 100' => ['100', 100.0],
            'integer 124' => [124, 124.0],
            'integer 0' => [0, 0.0],
            'integer -10' => [-10, -10.0],
            'integer -99' => [-99, -99.0],
            'float 3.5' => [3.5, 3.5],
            'string "13.5"' => ['13.5', 13.5],
            'string "-23.6"' => ['-23.6', -23.6]
        ];
    }

    public static function validateFailureProvider(): array
    {
        //input
        return [
            'string a' => ['a'],
            'string abc' => ['abc'],
            'hex string' => ['-0x'],
            'plus string' => ['+xyz'],
            'double plus string' => ['++30'],
            'exclusive minimum' => [-1000], //should fail because of exclusiveMinimum
            'out of bounds minimum' => [-10000000],
            'out of bounds maximum' => [10000000],
            'out of bounds string' => ['-1000000000']
        ];
    }

    public function testConstruct(): void
    {
        $validator = new NumberValidator(
            0,
            1
        );
        $this->assertInstanceOf(NumberValidator::class, $validator);
    }

    public function testConstructFailure1(): void
    {
        $this->expectException(\Exception::class);
        new NumberValidator(
            'a',
            1
        );
    }

    public function testConstructFailure2(): void
    {
        $this->expectException(\Exception::class);
        new NumberValidator(
            1,
            'a'
        );
    }

    public function testConstructFailure3(): void
    {
        $this->expectException(\Exception::class);
        new NumberValidator(
            1,
            2,
            'a'
        );
    }

    public function testConstructFailure4(): void
    {
        $this->expectException(\Exception::class);
        new NumberValidator(
            1,
            2,
            true,
            'a'
        );
    }

    public function testConstructFailure5(): void
    {
        $this->expectException(\Exception::class);
        new NumberValidator(
            1,
            2,
            true,
            true,
            'a'
        );
    }

    public function testConstructFailure6(): void
    {
        $this->expectException(\Exception::class);
        new NumberValidator(
            2,
            1
        );
    }

    #[DataProvider('validateSuccessProvider')]
    public function testCreateFromJSON(string|int|float $input, float $expected): void
    {
        $json = '{
            "type": "number",
            "minimum" : -1000,
            "maximum" : 1000,
            "title": "my number",
            "default": 10,
            "x-extra": "not existing"
        }';

        $validatorObject = NumberValidator::createFromJSON($json);

        $this->assertSame(
            'my number',
            $validatorObject->title,
            'Title must be passed'
        );

        $this->assertSame(
            10,
            $validatorObject->default,
            'Default must be passed'
        );

        $this->assertObjectNotHasProperty(
            'x-extra',
            $validatorObject,
            'Attribute must not exists'
        );

        //use helper function to validate $input against this validator
        $this->validateSuccess($validatorObject, $input, $expected);
    }

    /**
     * Helper method
     */
    private function validateSuccess(NumberValidator $object, string|int|float $input, float $expected): void
    {
        $return = $object->validate($input);

        $this->assertTrue($return->status);
        $this->assertIsFloat($return->value);
        $this->assertSame($expected, $return->value);
    }

    #[DataProvider('validateSuccessProvider')]
    public function testValidateSuccess(string|int|float $input, float $expected): void
    {
        $this->validateSuccess($this->object, $input, $expected);
    }

    #[DataProvider('validateFailureProvider')]
    public function testValidateFailure(mixed $input): void
    {
        $return = $this->object->validate($input);

        $this->assertFalse($return->status);
    }

    public function testValidateFailureMultipleOf(): void
    {
        $validator = new NumberValidator(null, null, null, null, 2);
        $return = $validator->validate(5);

        $this->assertFalse($return->status);

        $parameters = $return->errorObject->getParameters();

        $this->assertEquals('multipleOf', $parameters[0]['failure']);
    }

    /**
     * Validate against common enum keyword
     */
    public function testValidateCommon(): void
    {
        $validator = (new NumberValidator(0, 10));

        $validator->enum = [1, 3.5, 5];

        $return = $validator->validate(3.5);
        $this->assertTrue(
            $return->status,
            'Expect true since "3.5" is in enum array'
        );

        $return = $validator->validate(2);
        $this->assertFalse(
            $return->status,
            'Expect false since "2" is not in enum array'
        );
    }

    public function testGetType(): void
    {
        $this->assertEquals('number', $this->object->getType());
    }
}
