<?php

namespace Phramework\Validate;

use PHPUnit\Framework\Attributes\DataProvider;
use PHPUnit\Framework\TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015 - 2016-10-05 at 22:11:07.
 */
class StringValidatorTest extends TestCase
{

    /**
     * @var StringValidator
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new StringValidator(
            4,
            10,
            '/^[a-z][a-z0-9]{3,8}[0-9]$/'
        );
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
    }

    public static function validateSuccessProvider(): array
    {
        //input, expected
        return [
            'valid 1' => ['abx34scd3', 'abx34scd3'],
            'valid 2' => ['abcd0', 'abcd0'],
            'valid 3' => ['a2cx2', 'a2cx2'],
        ];
    }

    public static function validateFailureProvider(): array
    {
        //input
        return [
            'empty string' => [''],
            'object' => [new \stdClass()],
            'array' => [['x', 'array']], //because of type
            'integer 1' => [1], //because of type
            'integer 2' => [2],
            'integer -10' => [-10],
            'too short' => ['az9'], //because of minLength
            'pattern mismatch 1' => ['abc'], //because of pattern
            'pattern mismatch 2' => ['9abc4'], //because of pattern
            'too long' => ['asssssssssssssssssssbc9'], //because of maxLength
        ];
    }

    public function testConstruct(): void
    {
        $validator = new StringValidator();
        $this->assertInstanceOf(StringValidator::class, $validator);
    }

    public function testConstructFailure(): void
    {
        $this->expectException(\Exception::class);
        new StringValidator(-1);
    }

    public function testConstructFailure2(): void
    {
        $this->expectException(\Exception::class);
        new StringValidator(3, 2);
    }

    #[DataProvider('validateSuccessProvider')]
    public function testValidateSuccess(string $input, string $expected): void
    {
        $return = $this->object->validate($input);

        $this->assertIsString($return->value);
        $this->assertSame($expected, $return->value);
        $this->assertTrue($return->status);
    }

    public function testValidateSuccessRaw(): void
    {
        $this->object->raw = true;
        $return = $this->object->validate('abx34scd3');

        $this->assertIsString($return->value);
        $this->assertSame('abx34scd3', $return->value);
        $this->assertTrue($return->status);
    }

    #[DataProvider('validateFailureProvider')]
    public function testValidateFailure(mixed $input): void
    {
        $return = $this->object->validate($input);

        $this->assertFalse($return->status);
    }

    /**
     * Validate against common enum keyword
     */
    public function testValidateCommon(): void
    {
        $validator = (new StringValidator(0, 10));

        $validator->enum = ['aa', 'bb'];

        $return = $validator->validate('aa');
        $this->assertTrue(
            $return->status,
            'Expect true since "aa" is in enum array'
        );

        $return = $validator->validate('cc');
        $this->assertFalse(
            $return->status,
            'Expect false since "cc" is not in enum array'
        );
    }

    public function testGetType(): void
    {
        $this->assertEquals('string', $this->object->getType());
    }
}
