<?php

namespace Phramework\Validate;

use PHPUnit\Framework\Attributes\DataProvider;
use PHPUnit\Framework\TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015 - 2016-10-05 at 20:04:03.
 */
class UnsignedIntegerValidatorTest extends TestCase
{

    /**
     * @var UnsignedIntegerValidator
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new UnsignedIntegerValidator(10, 1000, true);
    }

    public static function validateSuccessProvider(): array
    {
        //input, expected
        return [
            'string 100' => ['100', 100],
            'integer 124' => [124, 124]
        ];
    }

    public static function validateFailureProvider(): array
    {
        //input
        return [
            'hex string' => ['-0x'],
            'alpha string' => ['abc'],
            'plus string' => ['+xyz'],
            'negative integer' => [-1000],
            'negative string' => ['-4'],
            'below minimum' => [4], //because of min
            'float value' => [1.4],
            'negative float' => [-13.5]
        ];
    }

    public function testConstruct(): void
    {
        $validator = new UnsignedIntegerValidator(
            0,
            1
        );
        $this->assertInstanceOf(UnsignedIntegerValidator::class, $validator);
    }

    public function testConstructFailure(): void
    {
        $this->expectException(\Exception::class);
        new UnsignedIntegerValidator(
            -1
        );
    }

    /**
     * Helper method
     */
    private function validateSuccess(UnsignedIntegerValidator $object, string|int $input, int $expected): void
    {
        $return = $object->validate($input);

        $this->assertTrue($return->status);
        $this->assertIsInt($return->value);
        $this->assertSame($expected, $return->value);
    }

    #[DataProvider('validateSuccessProvider')]
    public function testValidateSuccess(string|int $input, int $expected): void
    {
        $this->validateSuccess($this->object, $input, $expected);
    }

    #[DataProvider('validateFailureProvider')]
    public function testValidateFailure(mixed $input): void
    {
        $return = $this->object->validate($input);

        $this->assertFalse($return->status);
    }

    public function testCreateFromJSON(): void
    {
        $json = '{
            "type": "unsignedinteger"
        }';

        $validationObject = BaseValidator::createFromJSON($json);

        $this->assertInstanceOf(UnsignedIntegerValidator::class, $validationObject);
    }

    public function testCreateFromJSONAlias(): void
    {
        $json = '{
            "type": "uint"
        }';

        $validationObject = BaseValidator::createFromJSON($json);

        $this->assertInstanceOf(UnsignedIntegerValidator::class, $validationObject);
    }

    public function testGetType(): void
    {
        $this->assertSame('unsignedinteger', $this->object->getType());
    }
}
