<?php

namespace Phramework\Validate;

use PHPUnit\Framework\Attributes\DataProvider;
use PHPUnit\Framework\TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015 - 2016-10-05 at 22:11:07.
 */
class UsernameValidatorTest extends TestCase
{

    /**
     * @var UsernameValidator
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new UsernameValidator();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
        {
    }

    public static function validateSuccessProvider(): array
    {
        //input, expected
        return [
            'lowercase' => ['nohponex'],
            'mixed case' => ['NohponeX'],
            'with underscore' => ['nohp_onex'],
            'with dot' => ['nohp_o.nex']
        ];
    }

    public static function validateFailureProvider(): array
    {
        //input
        return [
            'too short' => ['ni'],
            'too long' => ['xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'],
            'invalid character epsilon' => ['nohponεξ'],
            'invalid character +' => ['+nohponex'],
            'invalid character @' => ['@nohponex'],
        ];
    }

    public function testConstruct(): void
    {
        $validator = new UsernameValidator();
        $this->assertInstanceOf(UsernameValidator::class, $validator);
    }

    #[DataProvider('validateSuccessProvider')]
    public function testValidateSuccess(string $input): void
    {
        $return = $this->object->validate($input);

        $this->assertIsString($return->value);
        $this->assertTrue($return->status);
    }

    #[DataProvider('validateFailureProvider')]
    public function testValidateFailure(string $input): void
    {
        $return = $this->object->validate($input);

        $this->assertFalse($return->status);
    }

    public function testCreateFromJSON(): void
    {
        $json = '{
            "type": "username"
        }';

        $validationObject = BaseValidator::createFromJSON($json);

        $this->assertInstanceOf(UsernameValidator::class, $validationObject);
    }

    public function testGetType(): void
    {
        $this->assertSame('username', $this->object->getType());
    }

    public function testGetAndSetUsernamePattern(): void
    {
        $originalPattern = UsernameValidator::getUsernamePattern();

        try {
            $pattern = '/^[a-z]+$/';
            UsernameValidator::setUsernamePattern($pattern);
            $this->assertSame($pattern, UsernameValidator::getUsernamePattern());
        } finally {
            //Restore original pattern to not affect other tests
            UsernameValidator::setUsernamePattern($originalPattern);
        }
    }
}

